import { test, expect } from '../fixtures'

/**
 * T601 — E2E Tests: Question Widget Lifecycle (MC / TF / Fill-in)
 *
 * Verifies that question blocks can be dragged onto the canvas,
 * that their default content renders correctly inside the GrapesJS iframe,
 * and that all three question types are discoverable in the block panel.
 *
 * Default content sourced from:
 *   packages/authoring-ui/src/types/questions.ts — MC_DEFAULT_EXTENDED,
 *   TF_DEFAULT_EXTENDED, FILL_DEFAULT_EXTENDED
 *
 * Preview HTML generated by:
 *   packages/authoring-ui/src/editor/registerQuestionBlocks.ts
 */

test.describe('Question Widget: Block Panel', () => {
  test.beforeEach(async ({ editorPage, page }) => {
    page.on('console', msg => {
      if (msg.type() === 'error') console.error('[BROWSER]', msg.text())
    })
    await editorPage.addSlide()
    await editorPage.waitForCanvas()
    // Switch to Blocks tab so question blocks are visible
    await editorPage.blocksTab.click()
    await page.waitForTimeout(500)
  })

  test('T601.0a — Multiple Choice block is visible in the Questions category', async ({ editorPage }) => {
    const block = editorPage.blockItem('Multiple Choice')
    await expect(block).toBeVisible({ timeout: 10_000 })
  })

  test('T601.0b — True / False block is visible in the Questions category', async ({ editorPage }) => {
    const block = editorPage.blockItem('True / False')
    await expect(block).toBeVisible({ timeout: 10_000 })
  })

  test('T601.0c — Fill in the Blank block is visible in the Questions category', async ({ editorPage }) => {
    const block = editorPage.blockItem('Fill in the Blank')
    await expect(block).toBeVisible({ timeout: 10_000 })
  })
})

test.describe('Question Widget: Multiple Choice (T601.1)', () => {
  test.beforeEach(async ({ editorPage, page }) => {
    page.on('console', msg => {
      if (msg.type() === 'error') console.error('[BROWSER]', msg.text())
    })
    await editorPage.addSlide()
    await editorPage.waitForCanvas()
  })

  test('T601.1 — MC widget appears in canvas after drag', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('Multiple Choice', 300, 200)

    const mc = editorPage.canvasComponent('[data-gjs-type="question-mc"]')
    await expect(mc).toBeVisible({ timeout: 15_000 })
  })

  test('T601.1a — MC widget renders default question text', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('Multiple Choice', 300, 200)

    const mc = editorPage.canvasComponent('[data-gjs-type="question-mc"]')
    await expect(mc).toBeVisible({ timeout: 15_000 })
    // Default question text from MC_DEFAULT_EXTENDED
    await expect(mc).toContainText('What is the correct answer?', { timeout: 10_000 })
  })

  test('T601.1b — MC widget renders 3 default answer options', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('Multiple Choice', 300, 200)

    const mc = editorPage.canvasComponent('[data-gjs-type="question-mc"]')
    await expect(mc).toBeVisible({ timeout: 15_000 })
    await expect(mc).toContainText('Option A', { timeout: 10_000 })
    await expect(mc).toContainText('Option B')
    await expect(mc).toContainText('Option C')
  })

  test('T601.1c — MC widget shows scoring hint (Multiple Choice label)', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('Multiple Choice', 300, 200)

    const mc = editorPage.canvasComponent('[data-gjs-type="question-mc"]')
    await expect(mc).toBeVisible({ timeout: 15_000 })
    await expect(mc).toContainText('Multiple Choice', { timeout: 10_000 })
  })
})

test.describe('Question Widget: True / False (T601.5)', () => {
  test.beforeEach(async ({ editorPage, page }) => {
    page.on('console', msg => {
      if (msg.type() === 'error') console.error('[BROWSER]', msg.text())
    })
    await editorPage.addSlide()
    await editorPage.waitForCanvas()
  })

  test('T601.5 — TF widget appears in canvas after drag', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('True / False', 300, 200)

    const tf = editorPage.canvasComponent('[data-gjs-type="question-tf"]')
    await expect(tf).toBeVisible({ timeout: 15_000 })
  })

  test('T601.5a — TF widget renders default question text', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('True / False', 300, 200)

    const tf = editorPage.canvasComponent('[data-gjs-type="question-tf"]')
    await expect(tf).toBeVisible({ timeout: 15_000 })
    // Default text from TF_DEFAULT_EXTENDED
    await expect(tf).toContainText('This statement is true.', { timeout: 10_000 })
  })

  test('T601.5b — TF widget renders True and False buttons', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('True / False', 300, 200)

    const tf = editorPage.canvasComponent('[data-gjs-type="question-tf"]')
    await expect(tf).toBeVisible({ timeout: 15_000 })
    await expect(tf).toContainText('True', { timeout: 10_000 })
    await expect(tf).toContainText('False')
  })

  test('T601.5c — TF widget shows True / False scoring hint label', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('True / False', 300, 200)

    const tf = editorPage.canvasComponent('[data-gjs-type="question-tf"]')
    await expect(tf).toBeVisible({ timeout: 15_000 })
    await expect(tf).toContainText('True / False', { timeout: 10_000 })
  })
})

test.describe('Question Widget: Fill in the Blank (T601.6)', () => {
  test.beforeEach(async ({ editorPage, page }) => {
    page.on('console', msg => {
      if (msg.type() === 'error') console.error('[BROWSER]', msg.text())
    })
    await editorPage.addSlide()
    await editorPage.waitForCanvas()
  })

  test('T601.6 — Fill widget appears in canvas after drag', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('Fill in the Blank', 300, 200)

    const fill = editorPage.canvasComponent('[data-gjs-type="question-fill"]')
    await expect(fill).toBeVisible({ timeout: 15_000 })
  })

  test('T601.6a — Fill widget renders default question text', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('Fill in the Blank', 300, 200)

    const fill = editorPage.canvasComponent('[data-gjs-type="question-fill"]')
    await expect(fill).toBeVisible({ timeout: 15_000 })
    // From FILL_DEFAULT_EXTENDED
    await expect(fill).toContainText('capital of France', { timeout: 10_000 })
  })

  test('T601.6b — Fill widget renders blank underline in preview', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('Fill in the Blank', 300, 200)

    const fill = editorPage.canvasComponent('[data-gjs-type="question-fill"]')
    await expect(fill).toBeVisible({ timeout: 15_000 })
    // The blank is rendered as a <span> with a bottom border — verify via DOM
    const blank = editorPage.canvasFrame().locator(
      '[data-gjs-type="question-fill"] span[style*="border-bottom"]',
    )
    await expect(blank).toBeVisible({ timeout: 10_000 })
  })

  test('T601.6c — Fill widget shows Fill in the Blank scoring hint label', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('Fill in the Blank', 300, 200)

    const fill = editorPage.canvasComponent('[data-gjs-type="question-fill"]')
    await expect(fill).toBeVisible({ timeout: 15_000 })
    await expect(fill).toContainText('Fill in the Blank', { timeout: 10_000 })
  })
})

// GAP-07 — Props panel edits are reflected in the canvas
// Verifies that editing via the right-sidebar Props panel updates the GrapesJS component
// model and the canvas re-renders the new text/options.
test.describe('Question Widget: Props Panel Editing (T601.2 / T601.3 / T601.4)', () => {
  test.beforeEach(async ({ editorPage, page }) => {
    page.on('console', msg => {
      if (msg.type() === 'error') console.error('[BROWSER]', msg.text())
    })
    await editorPage.addSlide()
    await editorPage.waitForCanvas()
  })

  test('T601.2 — MC question text edited via Props panel is reflected in the canvas', async ({ editorPage, page }) => {
    // Add widget programmatically for isolation (not testing drag here)
    await editorPage.addComponentViaEditor('question-mc')
    await page.waitForTimeout(300)

    // Open Props tab — the panel shows when a question widget is selected
    await editorPage.propsTab.click()
    const panel = page.locator('[data-testid="question-properties-panel"]')
    await panel.waitFor({ state: 'visible', timeout: 10_000 })

    // Edit the question text
    const textarea = panel.locator('textarea').first()
    await textarea.clear()
    await textarea.fill('Updated question text via E2E')
    await textarea.press('Tab')  // trigger onChange
    await page.waitForTimeout(500)

    // Verify the canvas renders the updated text
    const mc = editorPage.canvasComponent('[data-gjs-type="question-mc"]')
    await expect(mc).toContainText('Updated question text via E2E', { timeout: 5_000 })
  })

  test('T601.3a — clicking "+ Add" in MC options adds a 4th option visible in canvas', async ({ editorPage, page }) => {
    await editorPage.addComponentViaEditor('question-mc')
    await page.waitForTimeout(300)

    await editorPage.propsTab.click()
    const panel = page.locator('[data-testid="question-properties-panel"]')
    await panel.waitFor({ state: 'visible', timeout: 10_000 })

    // Default has 3 options (A, B, C) — click "+ Add"
    await panel.getByRole('button', { name: '+ Add' }).click()
    await page.waitForTimeout(500)

    // Canvas preview should now contain the new option text
    const mc = editorPage.canvasComponent('[data-gjs-type="question-mc"]')
    await expect(mc).toContainText('New option', { timeout: 5_000 })
  })

  test('T601.3b — removing an MC option removes it from the canvas', async ({ editorPage, page }) => {
    await editorPage.addComponentViaEditor('question-mc')
    await page.waitForTimeout(300)

    await editorPage.propsTab.click()
    const panel = page.locator('[data-testid="question-properties-panel"]')
    await panel.waitFor({ state: 'visible', timeout: 10_000 })

    // Default has 3 options; minimum enforced at 2, so Option C (3rd row) can be removed.
    // The ✕ buttons are in order: row 0 = Option A, row 1 = Option B, row 2 = Option C.
    const removeButtons = panel.locator('button[title="Remove"]')
    await expect(removeButtons).toHaveCount(3, { timeout: 5_000 })

    // Remove Option C (index 2)
    await removeButtons.nth(2).click()
    await page.waitForTimeout(500)

    // Canvas should no longer contain "Option C"
    const mc = editorPage.canvasComponent('[data-gjs-type="question-mc"]')
    await expect(mc).not.toContainText('Option C', { timeout: 5_000 })
    // Options A and B must remain
    await expect(mc).toContainText('Option A')
    await expect(mc).toContainText('Option B')
  })

  test('T601.4 — marking a different radio as correct updates the correct-answer indicator in canvas', async ({ editorPage, page }) => {
    await editorPage.addComponentViaEditor('question-mc')
    await page.waitForTimeout(300)

    await editorPage.propsTab.click()
    const panel = page.locator('[data-testid="question-properties-panel"]')
    await panel.waitFor({ state: 'visible', timeout: 10_000 })

    // Default: Option A (index 0) is correct.
    // Click the radio for Option B (index 1) to make it correct.
    const radios = panel.locator('input[type="radio"][title="Mark as correct"]')
    await expect(radios).toHaveCount(3, { timeout: 5_000 })
    await radios.nth(1).click()
    await page.waitForTimeout(500)

    // Verify the model reflects the change via window.__elearn_editor
    const correctText = await page.evaluate(() => {
      const ed = (window as Record<string, unknown>).__elearn_editor as {
        getSelected: () => { get: (k: string) => unknown } | null
      }
      const sel = ed?.getSelected()
      if (!sel) return null
      const ep = sel.get('extendedProperties') as { options: Array<{ text: string; isCorrect: boolean }> }
      return ep?.options?.find(o => o.isCorrect)?.text ?? null
    })
    expect(correctText).toBe('Option B')
  })
})

// T601.7 — Question widgets survive autosave + page reload
test.describe('Question Widget: Persistence (T601.7)', () => {
  test.beforeEach(async ({ editorPage, page }) => {
    page.on('console', msg => {
      if (msg.type() === 'error') console.error('[BROWSER]', msg.text())
    })
    await editorPage.addSlide()
    await editorPage.waitForCanvas()
  })

  test('T601.7 — MC question widget persists after page reload', async ({ editorPage, page }) => {
    // This test includes drag + PATCH wait + reload + canvas load — budget 60s total.
    test.setTimeout(60_000)

    // Capture our slide's index at the very START of the test body.
    // beforeEach just added this slide as the last one; slides are append-only so any
    // slides other workers add later will be at HIGHER indices. This index stays stable
    // across reload.
    const slides = page.locator('[data-testid="slide-item"]')
    const ourSlideIndex = (await slides.count()) - 1

    // Set up PATCH listener BEFORE drag so we cannot miss an early-fired autosave.
    const patchPromise = page.waitForResponse(
      resp => resp.url().includes('/courses') && resp.request().method() === 'PATCH',
      { timeout: 15_000 },
    )

    await editorPage.dragBlockToCanvas('Multiple Choice', 300, 200)
    const mc = editorPage.canvasComponent('[data-gjs-type="question-mc"]')
    await expect(mc).toBeVisible({ timeout: 15_000 })

    // Wait for autosave PATCH to confirm the widget was persisted to the backend.
    await patchPromise.catch(() => page.waitForTimeout(3000))  // fallback if PATCH already resolved

    // Reload — session is restored via refresh token (httpOnly cookie)
    await page.reload()
    await editorPage.waitForReloadComplete()

    // Navigate to our slide using the stable index captured before drag.
    // Slides are append-only; other workers' slides land at higher indices,
    // so ourSlideIndex remains valid after reload.
    await slides.nth(ourSlideIndex).click()
    await editorPage.waitForCanvas()

    // Widget must still be on the canvas
    await expect(editorPage.canvasComponent('[data-gjs-type="question-mc"]')).toBeVisible({ timeout: 15_000 })
    await expect(editorPage.canvasComponent('[data-gjs-type="question-mc"]')).toContainText(
      'What is the correct answer?',
      { timeout: 5_000 },
    )
  })

  // T601.8 — Verify that user-edited extendedProperties (question text) survive a page reload.
  // T601.7 only checks widget PRESENCE and the DEFAULT question text; this test verifies
  // that a user-modified value stored via QuestionPropertiesPanel is actually persisted.
  test('T601.8 — MC user-edited question text survives page reload (extendedProperties content)', async ({ editorPage, page }) => {
    // Generous budget: drag + PATCH wait (up to 15s) + reload + re-navigate is ~40s on slow CI.
    test.setTimeout(90_000)

    const slides = page.locator('[data-testid="slide-item"]')
    const ourSlideIndex = (await slides.count()) - 1

    await editorPage.dragBlockToCanvas('Multiple Choice', 300, 200)
    await expect(editorPage.canvasComponent('[data-gjs-type="question-mc"]')).toBeVisible({ timeout: 15_000 })

    // Click the MC widget to select it, then open the Props tab.
    await editorPage.canvasComponent('[data-gjs-type="question-mc"]').click()
    await editorPage.propsTab.click()

    const panel = page.locator('[data-testid="question-properties-panel"]')
    await expect(panel).toBeVisible({ timeout: 10_000 })

    // Set up PATCH listener BEFORE the edit. Autosave fires via 2s debounce on
    // component:update; the 20s timeout here gives ample margin in slow CI.
    const patchPromise = page.waitForResponse(
      resp => resp.url().includes('/courses') && resp.request().method() === 'PATCH',
      { timeout: 20_000 },
    )

    const textarea = panel.locator('textarea').first()
    await textarea.fill('T601.8 regression sentinel question text')
    await textarea.press('Tab')  // trigger onChange to flush to model

    // Wait for autosave PATCH; fall back to a 3s wait if it already resolved.
    await patchPromise.catch(() => page.waitForTimeout(3000))

    // Reload and navigate back to the same slide.
    await page.reload()
    await editorPage.waitForReloadComplete()
    await slides.nth(ourSlideIndex).click()
    await editorPage.waitForCanvas()

    // Re-select the widget and open Props tab to read the stored value.
    // After reload, GrapesJS needs a moment to fully set up canvas event listeners even
    // after data-editor-ready is true. We click then check for the panel; if it doesn't
    // appear (click landed before GrapesJS event system was ready), retry once.
    const questionComp = editorPage.canvasComponent('[data-gjs-type="question-mc"]')
    await expect(questionComp).toBeVisible({ timeout: 15_000 })
    await questionComp.click()
    await editorPage.propsTab.click()

    const restoredPanel = page.locator('[data-testid="question-properties-panel"]')
    const panelVisible = await restoredPanel.isVisible().catch(() => false)
    if (!panelVisible) {
      // Retry: GrapesJS event listeners may not have been ready on first click.
      await questionComp.click()
      await editorPage.propsTab.click()
    }
    await expect(restoredPanel).toBeVisible({ timeout: 10_000 })
    const restoredTextarea = restoredPanel.locator('textarea').first()

    // The textarea must contain the user-edited value, not the default placeholder.
    await expect(restoredTextarea).toHaveValue('T601.8 regression sentinel question text', { timeout: 10_000 })
  })
})

test.describe('Question Widget: Multiple widgets on same canvas', () => {
  test.beforeEach(async ({ editorPage, page }) => {
    page.on('console', msg => {
      if (msg.type() === 'error') console.error('[BROWSER]', msg.text())
    })
    await editorPage.addSlide()
    await editorPage.waitForCanvas()
  })

  test('T601.7 — All three question types can coexist on the same canvas', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('Multiple Choice', 100, 150)
    await expect(editorPage.canvasComponent('[data-gjs-type="question-mc"]')).toBeVisible({ timeout: 15_000 })

    await editorPage.dragBlockToCanvas('True / False', 500, 150)
    await expect(editorPage.canvasComponent('[data-gjs-type="question-tf"]')).toBeVisible({ timeout: 15_000 })

    await editorPage.dragBlockToCanvas('Fill in the Blank', 100, 400)
    await expect(editorPage.canvasComponent('[data-gjs-type="question-fill"]')).toBeVisible({ timeout: 15_000 })
  })
})

// T611-07 — Sidebar edit + fast slide switch race condition.
// QuestionPropertiesPanel calls editor.store() synchronously on every model.set().
// The slide-switch handler also calls editor.store() synchronously before loading
// the new slide. Either path must fire a PATCH within the test timeout.
// If this test fails: check that both synchronous store() call sites are still in place.
test.describe('Question Widget: Fast slide switch race condition (T611-07)', () => {
  test.beforeEach(async ({ editorPage, page }) => {
    page.on('console', msg => {
      if (msg.type() === 'error') console.error('[BROWSER]', msg.text())
    })
    await editorPage.addSlide()
    await editorPage.waitForCanvas()
  })

  test('T611-07 — extendedProperties edited in Props panel are preserved when switching slides before 2s debounce', async ({ editorPage, page }) => {
    test.setTimeout(60_000)

    const slides = page.locator('[data-testid="slide-item"]')
    const slideAIndex = (await slides.count()) - 1

    // Place an MC widget on slide A.
    await editorPage.dragBlockToCanvas('Multiple Choice', 300, 200)
    await expect(editorPage.canvasComponent('[data-gjs-type="question-mc"]')).toBeVisible({ timeout: 15_000 })

    // Select widget and open Props tab.
    await editorPage.canvasComponent('[data-gjs-type="question-mc"]').click()
    await editorPage.propsTab.click()

    const panel = page.locator('[data-testid="question-properties-panel"]')
    await expect(panel).toBeVisible({ timeout: 5_000 })

    // Set up a PATCH listener BEFORE the edit — QuestionPropertiesPanel calls
    // editor.store() synchronously after model.set(), so the PATCH can fire immediately.
    const patchPromise = page.waitForResponse(
      resp => resp.url().includes('/courses') && resp.request().method() === 'PATCH',
      { timeout: 15_000 },
    )

    const textarea = panel.locator('textarea').first()
    await textarea.fill('T611-07 race condition sentinel')
    await textarea.press('Tab')  // trigger onChange

    // Add slide B — addSlide() auto-navigates to the new slide, which is the rapid
    // switch being tested. Do NOT click slides.last() afterwards: addSlide() already
    // triggers editor.load() for slide B; a second click would cause a concurrent load
    // that corrupts GrapesJS internal state and crashes the editor.
    await editorPage.addSlide()
    await page.waitForTimeout(100)  // 100ms — far less than the 2s debounce

    // Wait for the PATCH that must have been triggered by the synchronous store() call.
    await patchPromise

    // Wait for slide B's canvas to be fully loaded before navigating away.
    // Without this, clicking slide A while slide B's editor.load() is still in-flight
    // causes concurrent GrapesJS loads that corrupt internal state and crash the editor.
    await editorPage.waitForCanvas()

    // Navigate back to slide A.
    await slides.nth(slideAIndex).click()
    await editorPage.waitForCanvas()
    // Give GrapesJS a moment to be fully interactive after the ready signal fires —
    // without this, click events inside the canvas iframe don't register as selections.
    await page.waitForTimeout(300)

    // Re-select the widget and verify the edited text is preserved.
    await expect(editorPage.canvasComponent('[data-gjs-type="question-mc"]')).toBeVisible({ timeout: 10_000 })
    await editorPage.canvasComponent('[data-gjs-type="question-mc"]').click()
    await editorPage.propsTab.click()

    const restoredPanel = page.locator('[data-testid="question-properties-panel"]')
    await expect(restoredPanel).toBeVisible({ timeout: 10_000 })
    const restoredTextarea = restoredPanel.locator('textarea').first()

    await expect(restoredTextarea).toHaveValue('T611-07 race condition sentinel', { timeout: 10_000 })
  })
})

// T611.10 — @regression: Mandatory question blocks Next button in linear-strict mode
// Verifies that when navigationMode is 'linear-strict' and a slide has a mandatory
// multiple choice question, the Next button in the runtime player is disabled until
// the question is answered. This prevents learners from progressing without completing
// required assessments.
test.describe('T611 — mandatory question navigation gate', () => {
  test.beforeEach(async ({ editorPage, page }) => {
    page.on('console', msg => {
      if (msg.type() === 'error') console.error('[BROWSER]', msg.text())
    })
    await editorPage.addSlide()
    await editorPage.waitForCanvas()
  })

  test('@regression T611.10 — Next button disabled until mandatory MC question is answered in linear-strict mode', async ({ editorPage, page, context }) => {
    test.setTimeout(90_000)

    // ── Step 1: Set navigation mode to linear-strict ──
    await editorPage.openCourseSettings()
    await editorPage.setNavigationMode('linear-strict')
    await editorPage.closeCourseSettings()

    // ── Step 2: Add a Multiple Choice question widget ──
    await editorPage.dragBlockToCanvas('Multiple Choice', 300, 200)
    const mc = editorPage.canvasComponent('[data-gjs-type="question-mc"]')
    await expect(mc).toBeVisible({ timeout: 15_000 })

    // ── Step 3: Select the question and mark it as mandatory ──
    await mc.click()
    await page.waitForTimeout(300)

    await editorPage.propsTab.click()
    const panel = page.locator('[data-testid="question-properties-panel"]')
    await expect(panel).toBeVisible({ timeout: 10_000 })

    // Find and check the mandatory checkbox
    const mandatoryCheckbox = panel.getByTestId('mandatory-checkbox')
    await expect(mandatoryCheckbox).toBeVisible({ timeout: 5_000 })
    const isChecked = await mandatoryCheckbox.isChecked()
    if (!isChecked) {
      await mandatoryCheckbox.click()
    }
    await page.waitForTimeout(500)  // Allow checkbox state to settle

    // Wait for autosave
    await page.waitForResponse(
      resp => resp.url().includes('/courses') && resp.request().method() === 'PATCH',
      { timeout: 15_000 },
    ).catch(() => page.waitForTimeout(1000))

    // ── Step 4: Open the preview in a new popup ──
    const [preview] = await Promise.all([
      context.waitForEvent('page'),
      editorPage.previewButton.click(),
    ])
    await preview.waitForLoadState('networkidle')

    // ── Step 5: Verify the Next button is disabled ──
    const nextBtn = preview.locator('[data-nav-next]')
    await expect(nextBtn).toBeVisible({ timeout: 10_000 })

    // Check that the button is disabled (has disabled attribute or opacity < 1)
    const isDisabled = await nextBtn.evaluate((el: HTMLElement) => {
      const btn = el as HTMLButtonElement
      return btn.disabled === true || window.getComputedStyle(btn).opacity === '0.4'
    })
    expect(isDisabled, 'Next button should be disabled when question is unanswered').toBe(true)

    // ── Step 6: Answer the question (click first radio option) ──
    // The runtime player renders the MC question; find and click a radio button
    const firstOption = preview.locator('input[type="radio"]').first()
    await expect(firstOption).toBeVisible({ timeout: 10_000 })
    await firstOption.click()

    // If there's a submit button for the question, click it
    const submitBtn = preview.locator('button:has-text("Submit")').first()
    if (await submitBtn.isVisible().catch(() => false)) {
      await submitBtn.click()
      await preview.waitForTimeout(500)  // Wait for submission processing
    }

    // ── Step 7: Verify the Next button is now enabled ──
    // Re-check the button's disabled state after answering
    const isNowEnabled = await nextBtn.evaluate((el: HTMLElement) => {
      const btn = el as HTMLButtonElement
      return btn.disabled === false && window.getComputedStyle(btn).opacity !== '0.4'
    })
    expect(isNowEnabled, 'Next button should be enabled after question is answered').toBe(true)

    // Clean up: close the preview popup
    await preview.close()
  })
})

// T620.5 — @regression: optimistic update in useComponentProperty prevents input bounce-back.
// Without the fix (setValue before comp.set), React would re-render the textarea with the
// stale Backbone model value, reverting the user's typed characters.
test.describe('Question Widget: Optimistic update — no bounce-back (T620.5)', () => {
  test.beforeEach(async ({ editorPage, page }) => {
    page.on('console', msg => {
      if (msg.type() === 'error') console.error('[BROWSER]', msg.text())
    })
    await editorPage.addSlide()
    await editorPage.waitForCanvas()
  })

  test('@regression T620.5 — rapid typing in MC question text shows no bounce-back (optimistic update)', async ({ editorPage, page }) => {
    test.setTimeout(60_000)

    await editorPage.dragBlockToCanvas('Multiple Choice', 300, 200)
    await expect(editorPage.canvasComponent('[data-gjs-type="question-mc"]')).toBeVisible({ timeout: 15_000 })

    await editorPage.canvasComponent('[data-gjs-type="question-mc"]').click()
    await editorPage.propsTab.click()

    const panel = page.locator('[data-testid="question-properties-panel"]')
    await expect(panel).toBeVisible({ timeout: 10_000 })

    const textarea = panel.locator('textarea').first()
    await textarea.clear()

    // Type quickly — without the optimistic update fix each character fires a
    // model:change event that would re-render and overwrite the typed value.
    const expected = 'T620.5 rapid typing regression sentinel'
    await textarea.pressSequentially(expected, { delay: 20 })

    // The textarea must hold the full typed string — no partial bounce-back.
    await expect(textarea).toHaveValue(expected, { timeout: 5_000 })
  })
})

// T621.5 — @regression: stale closure in useExtendedProperties.
// Without the fix, calling update() with new options would read the stale closure value
// of ep from the previous render, losing the concurrent question-text change.
test.describe('Question Widget: Stale closure — concurrent edit persistence (T621.5)', () => {
  test.beforeEach(async ({ editorPage, page }) => {
    page.on('console', msg => {
      if (msg.type() === 'error') console.error('[BROWSER]', msg.text())
    })
    await editorPage.addSlide()
    await editorPage.waitForCanvas()
  })

  test('@regression T621.5 — add MC option then change question text: both changes survive reload', async ({ editorPage, page }) => {
    test.setTimeout(90_000)

    const slides = page.locator('[data-testid="slide-item"]')
    const ourSlideIndex = (await slides.count()) - 1

    await editorPage.dragBlockToCanvas('Multiple Choice', 300, 200)
    await expect(editorPage.canvasComponent('[data-gjs-type="question-mc"]')).toBeVisible({ timeout: 15_000 })

    await editorPage.canvasComponent('[data-gjs-type="question-mc"]').click()
    await editorPage.propsTab.click()

    const panel = page.locator('[data-testid="question-properties-panel"]')
    await expect(panel).toBeVisible({ timeout: 10_000 })

    // Step 1: Add a 4th option (default has 3).
    await panel.getByRole('button', { name: '+ Add' }).click()
    await page.waitForTimeout(300)

    // Step 2: Immediately edit the question text — this is the concurrent write
    // that the stale-closure bug would cause to be lost on save.
    const textarea = panel.locator('textarea').first()
    await textarea.fill('T621.5 stale closure regression sentinel')
    await textarea.press('Tab')

    // Wait for autosave PATCH to confirm both changes reached the backend.
    const patchPromise = page.waitForResponse(
      resp => resp.url().includes('/courses') && resp.request().method() === 'PATCH',
      { timeout: 20_000 },
    )
    await patchPromise.catch(() => page.waitForTimeout(3000))

    // Reload and navigate back.
    await page.reload()
    await editorPage.waitForReloadComplete()
    await slides.nth(ourSlideIndex).click()
    await editorPage.waitForCanvas()

    // Re-select and open Props.
    const questionComp = editorPage.canvasComponent('[data-gjs-type="question-mc"]')
    await expect(questionComp).toBeVisible({ timeout: 15_000 })
    await questionComp.click()
    await editorPage.propsTab.click()

    const restoredPanel = page.locator('[data-testid="question-properties-panel"]')
    const panelVisible = await restoredPanel.isVisible().catch(() => false)
    if (!panelVisible) {
      await questionComp.click()
      await editorPage.propsTab.click()
    }
    await expect(restoredPanel).toBeVisible({ timeout: 10_000 })

    // Both changes must have survived: 4 options and the edited question text.
    const removeButtons = restoredPanel.locator('button[title="Remove"]')
    await expect(removeButtons).toHaveCount(4, { timeout: 5_000 })

    const restoredTextarea = restoredPanel.locator('textarea').first()
    await expect(restoredTextarea).toHaveValue('T621.5 stale closure regression sentinel', { timeout: 5_000 })
  })
})

// T631.3 — @regression: TF correct-answer radio persists across autosave + page reload.
// Default correctAnswer is true (True). We change it to false (False) and verify after reload.
test.describe('Question Widget: TF correct answer persistence across reload (T631.3)', () => {
  test.beforeEach(async ({ editorPage, page }) => {
    page.on('console', msg => {
      if (msg.type() === 'error') console.error('[BROWSER]', msg.text())
    })
    await editorPage.addSlide()
    await editorPage.waitForCanvas()
  })

  test('@regression T631.3 — TF correct-answer set to False survives autosave + page reload', async ({ editorPage, page }) => {
    test.setTimeout(120_000)

    const slides = page.locator('[data-testid="slide-item"]')
    const ourSlideIndex = (await slides.count()) - 1

    // Drag TF widget onto canvas.
    await editorPage.dragBlockToCanvas('True / False', 300, 200)
    const tf = editorPage.canvasComponent('[data-gjs-type="question-tf"]')
    await expect(tf).toBeVisible({ timeout: 15_000 })

    // Select widget and open Props panel.
    await tf.click()
    await editorPage.propsTab.click()
    const panel = page.locator('[data-testid="question-properties-panel"]')
    await expect(panel).toBeVisible({ timeout: 10_000 })

    // Default: True is correct (correctAnswer === true).
    // Change to False (the second radio in the Correct Answer section).
    // Use flat locator — avoids fragility of section-based text matching.
    const radios = panel.locator('input[type="radio"]')
    await expect(radios).toHaveCount(2, { timeout: 5_000 })

    // Set up PATCH listener BEFORE the click that triggers the autosave.
    const patchPromise = page.waitForResponse(
      resp => resp.url().includes('/courses') && resp.request().method() === 'PATCH',
      { timeout: 20_000 },
    )

    // radios.nth(0) = True, radios.nth(1) = False
    await radios.nth(1).click()
    await page.waitForTimeout(300)

    // Confirm model reflects the change before saving.
    const correctBeforeSave = await page.evaluate(() => {
      const ed = (window as Record<string, unknown>).__elearn_editor as {
        getSelected: () => { get: (k: string) => unknown } | null
      }
      const sel = ed?.getSelected()
      if (!sel) return null
      const ep = sel.get('extendedProperties') as { correctAnswer: boolean }
      return ep?.correctAnswer ?? null
    })
    expect(correctBeforeSave).toBe(false)

    // Wait for autosave PATCH (already set up before the click).
    await patchPromise.catch(() => page.waitForTimeout(3000))

    // Reload and navigate back.
    await page.reload()
    await editorPage.waitForReloadComplete()
    await slides.nth(ourSlideIndex).click()
    await page.waitForTimeout(500)
    await editorPage.waitForCanvas()

    // Re-select widget and open Props.
    const tfComp = editorPage.canvasComponent('[data-gjs-type="question-tf"]')
    await expect(tfComp).toBeVisible({ timeout: 15_000 })
    await tfComp.click()
    await editorPage.propsTab.click()

    const restoredPanel = page.locator('[data-testid="question-properties-panel"]')
    if (!(await restoredPanel.isVisible().catch(() => false))) {
      await tfComp.click()
      await editorPage.propsTab.click()
    }
    await expect(restoredPanel).toBeVisible({ timeout: 10_000 })

    // correctAnswer must still be false after reload.
    const correctAfterReload = await page.evaluate(() => {
      const ed = (window as Record<string, unknown>).__elearn_editor as {
        getSelected: () => { get: (k: string) => unknown } | null
      }
      const sel = ed?.getSelected()
      if (!sel) return null
      const ep = sel.get('extendedProperties') as { correctAnswer: boolean }
      return ep?.correctAnswer ?? null
    })
    expect(correctAfterReload).toBe(false)
  })
})

// T631.4 — @regression: Fill accepted answer persists across autosave + page reload.
// Default answer is 'Paris'. We replace it with a unique sentinel value.
test.describe('Question Widget: Fill accepted answer persistence across reload (T631.4)', () => {
  test.beforeEach(async ({ editorPage, page }) => {
    page.on('console', msg => {
      if (msg.type() === 'error') console.error('[BROWSER]', msg.text())
    })
    await editorPage.addSlide()
    await editorPage.waitForCanvas()
  })

  test('@regression T631.4 — Fill accepted answer survives autosave + page reload', async ({ editorPage, page }) => {
    test.setTimeout(90_000)

    const slides = page.locator('[data-testid="slide-item"]')
    const ourSlideIndex = (await slides.count()) - 1

    // Drag Fill widget onto canvas.
    await editorPage.dragBlockToCanvas('Fill in the Blank', 300, 200)
    const fill = editorPage.canvasComponent('[data-gjs-type="question-fill"]')
    await expect(fill).toBeVisible({ timeout: 15_000 })

    // Select widget and open Props panel.
    await fill.click()
    await editorPage.propsTab.click()
    const panel = page.locator('[data-testid="question-properties-panel"]')
    await expect(panel).toBeVisible({ timeout: 10_000 })

    // Clear the first accepted answer field and type the sentinel value.
    const answerInput = panel.locator('input[placeholder="Accepted answer"]').first()
    await expect(answerInput).toBeVisible({ timeout: 5_000 })
    await answerInput.fill('T631.4 sentinel')
    await answerInput.press('Tab')
    await page.waitForTimeout(300)

    // Confirm model reflects the change before saving.
    const answersBeforeSave = await page.evaluate(() => {
      const ed = (window as Record<string, unknown>).__elearn_editor as {
        getSelected: () => { get: (k: string) => unknown } | null
      }
      const sel = ed?.getSelected()
      if (!sel) return null
      const ep = sel.get('extendedProperties') as { answers: string[] }
      return ep?.answers ?? null
    })
    expect(answersBeforeSave?.[0]).toBe('T631.4 sentinel')

    // Wait for autosave PATCH.
    const patchPromise = page.waitForResponse(
      resp => resp.url().includes('/courses') && resp.request().method() === 'PATCH',
      { timeout: 20_000 },
    )
    await patchPromise.catch(() => page.waitForTimeout(3000))

    // Reload and navigate back.
    await page.reload()
    await editorPage.waitForReloadComplete()
    await slides.nth(ourSlideIndex).click()
    await editorPage.waitForCanvas()

    // Re-select widget and open Props.
    const fillComp = editorPage.canvasComponent('[data-gjs-type="question-fill"]')
    await expect(fillComp).toBeVisible({ timeout: 15_000 })
    await fillComp.click()
    await editorPage.propsTab.click()

    const restoredPanel = page.locator('[data-testid="question-properties-panel"]')
    if (!(await restoredPanel.isVisible().catch(() => false))) {
      await fillComp.click()
      await editorPage.propsTab.click()
    }
    await expect(restoredPanel).toBeVisible({ timeout: 10_000 })

    // First accepted answer must still be the sentinel after reload.
    const answersAfterReload = await page.evaluate(() => {
      const ed = (window as Record<string, unknown>).__elearn_editor as {
        getSelected: () => { get: (k: string) => unknown } | null
      }
      const sel = ed?.getSelected()
      if (!sel) return null
      const ep = sel.get('extendedProperties') as { answers: string[] }
      return ep?.answers ?? null
    })
    expect(answersAfterReload?.[0]).toBe('T631.4 sentinel')
  })
})

// T631.6 — @regression: MC correct-answer radio persists across autosave + page reload.
// Without the fix, the `extendedProperties` update might not reach the model, causing the
// correct-answer selection to revert to the default (Option A) after a reload.
test.describe('Question Widget: Correct answer persistence across reload (T631.6)', () => {
  test.beforeEach(async ({ editorPage, page }) => {
    page.on('console', msg => {
      if (msg.type() === 'error') console.error('[BROWSER]', msg.text())
    })
    await editorPage.addSlide()
    await editorPage.waitForCanvas()
  })

  test('@regression T631.6 — MC correct-answer radio marked as Option B survives autosave + page reload', async ({ editorPage, page }) => {
    test.setTimeout(90_000)

    const slides = page.locator('[data-testid="slide-item"]')
    const ourSlideIndex = (await slides.count()) - 1

    // Drag MC widget onto canvas.
    await editorPage.dragBlockToCanvas('Multiple Choice', 300, 200)
    const mc = editorPage.canvasComponent('[data-gjs-type="question-mc"]')
    await expect(mc).toBeVisible({ timeout: 15_000 })

    // Select widget and open Props panel.
    await mc.click()
    await editorPage.propsTab.click()
    const panel = page.locator('[data-testid="question-properties-panel"]')
    await expect(panel).toBeVisible({ timeout: 10_000 })

    // Default: Option A (index 0) is correct.
    // Mark Option B (index 1) as the correct answer.
    const radios = panel.locator('input[type="radio"][title="Mark as correct"]')
    await expect(radios).toHaveCount(3, { timeout: 5_000 })
    await radios.nth(1).click()
    await page.waitForTimeout(300)

    // Confirm the model reflects the change before saving.
    const correctTextBeforeSave = await page.evaluate(() => {
      const ed = (window as Record<string, unknown>).__elearn_editor as {
        getSelected: () => { get: (k: string) => unknown } | null
      }
      const sel = ed?.getSelected()
      if (!sel) return null
      const ep = sel.get('extendedProperties') as { options: Array<{ text: string; isCorrect: boolean }> }
      return ep?.options?.find(o => o.isCorrect)?.text ?? null
    })
    expect(correctTextBeforeSave).toBe('Option B')

    // Wait for autosave PATCH to reach the backend.
    const patchPromise = page.waitForResponse(
      resp => resp.url().includes('/courses') && resp.request().method() === 'PATCH',
      { timeout: 20_000 },
    )
    await patchPromise.catch(() => page.waitForTimeout(3000))

    // Reload and navigate back to our slide.
    await page.reload()
    await editorPage.waitForReloadComplete()
    await slides.nth(ourSlideIndex).click()
    await editorPage.waitForCanvas()

    // Re-select the widget and open Props.
    const questionComp = editorPage.canvasComponent('[data-gjs-type="question-mc"]')
    await expect(questionComp).toBeVisible({ timeout: 15_000 })
    await questionComp.click()
    await editorPage.propsTab.click()

    const restoredPanel = page.locator('[data-testid="question-properties-panel"]')
    if (!(await restoredPanel.isVisible().catch(() => false))) {
      await questionComp.click()
      await editorPage.propsTab.click()
    }
    await expect(restoredPanel).toBeVisible({ timeout: 10_000 })

    // Option B must still be the correct answer after reload.
    const correctTextAfterReload = await page.evaluate(() => {
      const ed = (window as Record<string, unknown>).__elearn_editor as {
        getSelected: () => { get: (k: string) => unknown } | null
      }
      const sel = ed?.getSelected()
      if (!sel) return null
      const ep = sel.get('extendedProperties') as { options: Array<{ text: string; isCorrect: boolean }> }
      return ep?.options?.find(o => o.isCorrect)?.text ?? null
    })
    expect(correctTextAfterReload).toBe('Option B')
  })
})

// T639.8 — @regression: getLatest() prevents stale-closure clobber when question text is
// edited THEN an option is added in rapid succession (reverse order of T621.5).
//
// Without the T639 fix, `update({ options: [...] })` would spread over the stale closure
// value of `ep` (captured before the question-text change committed) and silently clobber
// the question text. With `getLatest()`, the second update reads `latestRef.current` —
// the committed post-first-update value — so both changes survive.
test.describe('Question Widget: getLatest() stale-closure regression — text then option (T639.8)', () => {
  test.beforeEach(async ({ editorPage, page }) => {
    page.on('console', msg => {
      if (msg.type() === 'error') console.error('[BROWSER]', msg.text())
    })
    await editorPage.addSlide()
    await editorPage.waitForCanvas()
  })

  test('@regression T639 — change question text then add option: both changes survive reload', async ({ editorPage, page }) => {
    test.setTimeout(90_000)

    const slides = page.locator('[data-testid="slide-item"]')
    const ourSlideIndex = (await slides.count()) - 1

    await editorPage.dragBlockToCanvas('Multiple Choice', 300, 200)
    await expect(editorPage.canvasComponent('[data-gjs-type="question-mc"]')).toBeVisible({ timeout: 15_000 })

    await editorPage.canvasComponent('[data-gjs-type="question-mc"]').click()
    await editorPage.propsTab.click()

    const panel = page.locator('[data-testid="question-properties-panel"]')
    await expect(panel).toBeVisible({ timeout: 10_000 })

    // Step 1: Edit question text first. This fires setEp({ ...getLatest(), questionText: '...' }).
    const textarea = panel.locator('textarea').first()
    await textarea.fill('T639 regression sentinel question text')
    await textarea.press('Tab')

    // Step 2: Immediately add a 4th option — fires setEp({ ...getLatest(), options: [...] }).
    // With the stale-closure bug, this second update would spread over pre-step-1 ep,
    // overwriting questionText back to the empty default.
    await panel.getByRole('button', { name: '+ Add' }).click()
    await page.waitForTimeout(300)

    // Verify both are present in the model before autosave.
    const beforeSave = await page.evaluate(() => {
      const ed = (window as Record<string, unknown>).__elearn_editor as {
        getSelected: () => { get: (k: string) => unknown } | null
      }
      const sel = ed?.getSelected()
      if (!sel) return null
      const ep = sel.get('extendedProperties') as {
        questionText: string
        options: unknown[]
      }
      return { questionText: ep?.questionText ?? null, optionCount: ep?.options?.length ?? 0 }
    })
    expect(beforeSave?.questionText).toBe('T639 regression sentinel question text')
    expect(beforeSave?.optionCount).toBe(4)

    // Wait for autosave PATCH to reach the backend.
    const patchPromise = page.waitForResponse(
      resp => resp.url().includes('/courses') && resp.request().method() === 'PATCH',
      { timeout: 20_000 },
    )
    await patchPromise.catch(() => page.waitForTimeout(3000))

    // Reload and navigate back to our slide.
    await page.reload()
    await editorPage.waitForReloadComplete()
    await slides.nth(ourSlideIndex).click()
    await editorPage.waitForCanvas()

    // Re-select and open Props.
    const questionComp = editorPage.canvasComponent('[data-gjs-type="question-mc"]')
    await expect(questionComp).toBeVisible({ timeout: 15_000 })
    await questionComp.click()
    await editorPage.propsTab.click()

    const restoredPanel = page.locator('[data-testid="question-properties-panel"]')
    if (!(await restoredPanel.isVisible().catch(() => false))) {
      await questionComp.click()
      await editorPage.propsTab.click()
    }
    await expect(restoredPanel).toBeVisible({ timeout: 10_000 })

    // Both changes must have survived: 4 options AND the question text.
    const removeButtons = restoredPanel.locator('button[title="Remove"]')
    await expect(removeButtons).toHaveCount(4, { timeout: 5_000 })

    const restoredTextarea = restoredPanel.locator('textarea').first()
    await expect(restoredTextarea).toHaveValue('T639 regression sentinel question text', { timeout: 5_000 })
  })
})
