import { test, expect } from '../fixtures'

/**
 * T601 — E2E Tests: Question Widget Lifecycle (MC / TF / Fill-in)
 *
 * Verifies that question blocks can be dragged onto the canvas,
 * that their default content renders correctly inside the GrapesJS iframe,
 * and that all three question types are discoverable in the block panel.
 *
 * Default content sourced from:
 *   packages/authoring-ui/src/types/questions.ts — MC_DEFAULT_EXTENDED,
 *   TF_DEFAULT_EXTENDED, FILL_DEFAULT_EXTENDED
 *
 * Preview HTML generated by:
 *   packages/authoring-ui/src/editor/registerQuestionBlocks.ts
 */

test.describe('Question Widget: Block Panel', () => {
  test.beforeEach(async ({ editorPage, page }) => {
    page.on('console', msg => {
      if (msg.type() === 'error') console.log(`[BROWSER ERROR] ${msg.text()}`)
    })
    await editorPage.addSlide()
    await editorPage.waitForCanvas()
    // Switch to Blocks tab so question blocks are visible
    await editorPage.blocksTab.click()
    await page.waitForTimeout(500)
  })

  test('T601.0a — Multiple Choice block is visible in the Questions category', async ({ editorPage }) => {
    const block = editorPage.blockItem('Multiple Choice')
    await expect(block).toBeVisible({ timeout: 10_000 })
  })

  test('T601.0b — True / False block is visible in the Questions category', async ({ editorPage }) => {
    const block = editorPage.blockItem('True / False')
    await expect(block).toBeVisible({ timeout: 10_000 })
  })

  test('T601.0c — Fill in the Blank block is visible in the Questions category', async ({ editorPage }) => {
    const block = editorPage.blockItem('Fill in the Blank')
    await expect(block).toBeVisible({ timeout: 10_000 })
  })
})

test.describe('Question Widget: Multiple Choice (T601.1)', () => {
  test.beforeEach(async ({ editorPage, page }) => {
    page.on('console', msg => {
      if (msg.type() === 'error') console.log(`[BROWSER ERROR] ${msg.text()}`)
    })
    await editorPage.addSlide()
    await editorPage.waitForCanvas()
  })

  test('T601.1 — MC widget appears in canvas after drag', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('Multiple Choice', 300, 200)

    const mc = editorPage.canvasComponent('[data-gjs-type="question-mc"]')
    await expect(mc).toBeVisible({ timeout: 15_000 })
  })

  test('T601.1a — MC widget renders default question text', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('Multiple Choice', 300, 200)

    const mc = editorPage.canvasComponent('[data-gjs-type="question-mc"]')
    await expect(mc).toBeVisible({ timeout: 15_000 })
    // Default question text from MC_DEFAULT_EXTENDED
    await expect(mc).toContainText('What is the correct answer?', { timeout: 10_000 })
  })

  test('T601.1b — MC widget renders 3 default answer options', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('Multiple Choice', 300, 200)

    const mc = editorPage.canvasComponent('[data-gjs-type="question-mc"]')
    await expect(mc).toBeVisible({ timeout: 15_000 })
    await expect(mc).toContainText('Option A', { timeout: 10_000 })
    await expect(mc).toContainText('Option B')
    await expect(mc).toContainText('Option C')
  })

  test('T601.1c — MC widget shows scoring hint (Multiple Choice label)', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('Multiple Choice', 300, 200)

    const mc = editorPage.canvasComponent('[data-gjs-type="question-mc"]')
    await expect(mc).toBeVisible({ timeout: 15_000 })
    await expect(mc).toContainText('Multiple Choice', { timeout: 10_000 })
  })
})

test.describe('Question Widget: True / False (T601.5)', () => {
  test.beforeEach(async ({ editorPage, page }) => {
    page.on('console', msg => {
      if (msg.type() === 'error') console.log(`[BROWSER ERROR] ${msg.text()}`)
    })
    await editorPage.addSlide()
    await editorPage.waitForCanvas()
  })

  test('T601.5 — TF widget appears in canvas after drag', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('True / False', 300, 200)

    const tf = editorPage.canvasComponent('[data-gjs-type="question-tf"]')
    await expect(tf).toBeVisible({ timeout: 15_000 })
  })

  test('T601.5a — TF widget renders default question text', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('True / False', 300, 200)

    const tf = editorPage.canvasComponent('[data-gjs-type="question-tf"]')
    await expect(tf).toBeVisible({ timeout: 15_000 })
    // Default text from TF_DEFAULT_EXTENDED
    await expect(tf).toContainText('This statement is true.', { timeout: 10_000 })
  })

  test('T601.5b — TF widget renders True and False buttons', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('True / False', 300, 200)

    const tf = editorPage.canvasComponent('[data-gjs-type="question-tf"]')
    await expect(tf).toBeVisible({ timeout: 15_000 })
    await expect(tf).toContainText('True', { timeout: 10_000 })
    await expect(tf).toContainText('False')
  })

  test('T601.5c — TF widget shows True / False scoring hint label', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('True / False', 300, 200)

    const tf = editorPage.canvasComponent('[data-gjs-type="question-tf"]')
    await expect(tf).toBeVisible({ timeout: 15_000 })
    await expect(tf).toContainText('True / False', { timeout: 10_000 })
  })
})

test.describe('Question Widget: Fill in the Blank (T601.6)', () => {
  test.beforeEach(async ({ editorPage, page }) => {
    page.on('console', msg => {
      if (msg.type() === 'error') console.log(`[BROWSER ERROR] ${msg.text()}`)
    })
    await editorPage.addSlide()
    await editorPage.waitForCanvas()
  })

  test('T601.6 — Fill widget appears in canvas after drag', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('Fill in the Blank', 300, 200)

    const fill = editorPage.canvasComponent('[data-gjs-type="question-fill"]')
    await expect(fill).toBeVisible({ timeout: 15_000 })
  })

  test('T601.6a — Fill widget renders default question text', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('Fill in the Blank', 300, 200)

    const fill = editorPage.canvasComponent('[data-gjs-type="question-fill"]')
    await expect(fill).toBeVisible({ timeout: 15_000 })
    // From FILL_DEFAULT_EXTENDED
    await expect(fill).toContainText('capital of France', { timeout: 10_000 })
  })

  test('T601.6b — Fill widget renders blank underline in preview', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('Fill in the Blank', 300, 200)

    const fill = editorPage.canvasComponent('[data-gjs-type="question-fill"]')
    await expect(fill).toBeVisible({ timeout: 15_000 })
    // The blank is rendered as a <span> with a bottom border — verify via DOM
    const blank = editorPage.canvasFrame().locator(
      '[data-gjs-type="question-fill"] span[style*="border-bottom"]',
    )
    await expect(blank).toBeVisible({ timeout: 10_000 })
  })

  test('T601.6c — Fill widget shows Fill in the Blank scoring hint label', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('Fill in the Blank', 300, 200)

    const fill = editorPage.canvasComponent('[data-gjs-type="question-fill"]')
    await expect(fill).toBeVisible({ timeout: 15_000 })
    await expect(fill).toContainText('Fill in the Blank', { timeout: 10_000 })
  })
})

// GAP-07 — Props panel edits are reflected in the canvas
// Verifies that editing via the right-sidebar Props panel updates the GrapesJS component
// model and the canvas re-renders the new text/options.
test.describe('Question Widget: Props Panel Editing (T601.2 / T601.3 / T601.4)', () => {
  test.beforeEach(async ({ editorPage, page }) => {
    page.on('console', msg => {
      if (msg.type() === 'error') console.log(`[BROWSER ERROR] ${msg.text()}`)
    })
    await editorPage.addSlide()
    await editorPage.waitForCanvas()
  })

  test('T601.2 — MC question text edited via Props panel is reflected in the canvas', async ({ editorPage, page }) => {
    // Add widget programmatically for isolation (not testing drag here)
    await editorPage.addComponentViaEditor('question-mc')
    await page.waitForTimeout(300)

    // Open Props tab — the panel shows when a question widget is selected
    await editorPage.propsTab.click()
    const panel = page.locator('[data-testid="question-properties-panel"]')
    await panel.waitFor({ state: 'visible', timeout: 10_000 })

    // Edit the question text
    const textarea = panel.locator('textarea').first()
    await textarea.clear()
    await textarea.fill('Updated question text via E2E')
    await textarea.press('Tab')  // trigger onChange
    await page.waitForTimeout(500)

    // Verify the canvas renders the updated text
    const mc = editorPage.canvasComponent('[data-gjs-type="question-mc"]')
    await expect(mc).toContainText('Updated question text via E2E', { timeout: 5_000 })
  })

  test('T601.3a — clicking "+ Add" in MC options adds a 4th option visible in canvas', async ({ editorPage, page }) => {
    await editorPage.addComponentViaEditor('question-mc')
    await page.waitForTimeout(300)

    await editorPage.propsTab.click()
    const panel = page.locator('[data-testid="question-properties-panel"]')
    await panel.waitFor({ state: 'visible', timeout: 10_000 })

    // Default has 3 options (A, B, C) — click "+ Add"
    await panel.getByRole('button', { name: '+ Add' }).click()
    await page.waitForTimeout(500)

    // Canvas preview should now contain the new option text
    const mc = editorPage.canvasComponent('[data-gjs-type="question-mc"]')
    await expect(mc).toContainText('New option', { timeout: 5_000 })
  })

  test('T601.3b — removing an MC option removes it from the canvas', async ({ editorPage, page }) => {
    await editorPage.addComponentViaEditor('question-mc')
    await page.waitForTimeout(300)

    await editorPage.propsTab.click()
    const panel = page.locator('[data-testid="question-properties-panel"]')
    await panel.waitFor({ state: 'visible', timeout: 10_000 })

    // Default has 3 options; minimum enforced at 2, so Option C (3rd row) can be removed.
    // The ✕ buttons are in order: row 0 = Option A, row 1 = Option B, row 2 = Option C.
    const removeButtons = panel.locator('button[title="Remove"]')
    await expect(removeButtons).toHaveCount(3, { timeout: 5_000 })

    // Remove Option C (index 2)
    await removeButtons.nth(2).click()
    await page.waitForTimeout(500)

    // Canvas should no longer contain "Option C"
    const mc = editorPage.canvasComponent('[data-gjs-type="question-mc"]')
    await expect(mc).not.toContainText('Option C', { timeout: 5_000 })
    // Options A and B must remain
    await expect(mc).toContainText('Option A')
    await expect(mc).toContainText('Option B')
  })

  test('T601.4 — marking a different radio as correct updates the correct-answer indicator in canvas', async ({ editorPage, page }) => {
    await editorPage.addComponentViaEditor('question-mc')
    await page.waitForTimeout(300)

    await editorPage.propsTab.click()
    const panel = page.locator('[data-testid="question-properties-panel"]')
    await panel.waitFor({ state: 'visible', timeout: 10_000 })

    // Default: Option A (index 0) is correct.
    // Click the radio for Option B (index 1) to make it correct.
    const radios = panel.locator('input[type="radio"][title="Mark as correct"]')
    await expect(radios).toHaveCount(3, { timeout: 5_000 })
    await radios.nth(1).click()
    await page.waitForTimeout(500)

    // Verify the model reflects the change via window.__elearn_editor
    const correctText = await page.evaluate(() => {
      const ed = (window as Record<string, unknown>).__elearn_editor as {
        getSelected: () => { get: (k: string) => unknown } | null
      }
      const sel = ed?.getSelected()
      if (!sel) return null
      const ep = sel.get('extendedProperties') as { options: Array<{ text: string; isCorrect: boolean }> }
      return ep?.options?.find(o => o.isCorrect)?.text ?? null
    })
    expect(correctText).toBe('Option B')
  })
})

// T601.7 — Question widgets survive autosave + page reload
test.describe('Question Widget: Persistence (T601.7)', () => {
  test.beforeEach(async ({ editorPage, page }) => {
    page.on('console', msg => {
      if (msg.type() === 'error') console.log(`[BROWSER ERROR] ${msg.text()}`)
    })
    await editorPage.addSlide()
    await editorPage.waitForCanvas()
  })

  test('T601.7 — MC question widget persists after page reload', async ({ editorPage, page }) => {
    // This test includes drag + PATCH wait + reload + canvas load — budget 60s total.
    test.setTimeout(60_000)

    // Capture our slide's index at the very START of the test body.
    // beforeEach just added this slide as the last one; slides are append-only so any
    // slides other workers add later will be at HIGHER indices. This index stays stable
    // across reload.
    const slides = page.locator('[data-testid="slide-item"]')
    const ourSlideIndex = (await slides.count()) - 1

    // Set up PATCH listener BEFORE drag so we cannot miss an early-fired autosave.
    const patchPromise = page.waitForResponse(
      resp => resp.url().includes('/courses') && resp.request().method() === 'PATCH',
      { timeout: 15_000 },
    )

    await editorPage.dragBlockToCanvas('Multiple Choice', 300, 200)
    const mc = editorPage.canvasComponent('[data-gjs-type="question-mc"]')
    await expect(mc).toBeVisible({ timeout: 15_000 })

    // Wait for autosave PATCH to confirm the widget was persisted to the backend.
    await patchPromise.catch(() => page.waitForTimeout(3000))  // fallback if PATCH already resolved

    // Reload — session is restored via refresh token (httpOnly cookie)
    await page.reload()
    await editorPage.waitForReloadComplete()

    // Navigate to our slide using the stable index captured before drag.
    // Slides are append-only; other workers' slides land at higher indices,
    // so ourSlideIndex remains valid after reload.
    await slides.nth(ourSlideIndex).click()
    await editorPage.waitForCanvas()

    // Widget must still be on the canvas
    await expect(editorPage.canvasComponent('[data-gjs-type="question-mc"]')).toBeVisible({ timeout: 15_000 })
    await expect(editorPage.canvasComponent('[data-gjs-type="question-mc"]')).toContainText(
      'What is the correct answer?',
      { timeout: 5_000 },
    )
  })

  // T601.8 — Verify that user-edited extendedProperties (question text) survive a page reload.
  // T601.7 only checks widget PRESENCE and the DEFAULT question text; this test verifies
  // that a user-modified value stored via QuestionPropertiesPanel is actually persisted.
  test('T601.8 — MC user-edited question text survives page reload (extendedProperties content)', async ({ editorPage, page }) => {
    // Generous budget: drag + PATCH wait (up to 15s) + reload + re-navigate is ~40s on slow CI.
    test.setTimeout(90_000)

    const slides = page.locator('[data-testid="slide-item"]')
    const ourSlideIndex = (await slides.count()) - 1

    await editorPage.dragBlockToCanvas('Multiple Choice', 300, 200)
    await expect(editorPage.canvasComponent('[data-gjs-type="question-mc"]')).toBeVisible({ timeout: 15_000 })

    // Click the MC widget to select it, then open the Props tab.
    await editorPage.canvasComponent('[data-gjs-type="question-mc"]').click()
    await editorPage.propsTab.click()

    const panel = page.locator('[data-testid="question-properties-panel"]')
    await expect(panel).toBeVisible({ timeout: 10_000 })

    // Set up PATCH listener BEFORE the edit. Autosave fires via 2s debounce on
    // component:update; the 20s timeout here gives ample margin in slow CI.
    const patchPromise = page.waitForResponse(
      resp => resp.url().includes('/courses') && resp.request().method() === 'PATCH',
      { timeout: 20_000 },
    )

    const textarea = panel.locator('textarea').first()
    await textarea.fill('T601.8 regression sentinel question text')
    await textarea.press('Tab')  // trigger onChange to flush to model

    // Wait for autosave PATCH; fall back to a 3s wait if it already resolved.
    await patchPromise.catch(() => page.waitForTimeout(3000))

    // Reload and navigate back to the same slide.
    await page.reload()
    await editorPage.waitForReloadComplete()
    await slides.nth(ourSlideIndex).click()
    await editorPage.waitForCanvas()

    // Re-select the widget and open Props tab to read the stored value.
    // After reload, GrapesJS needs a moment to fully set up canvas event listeners even
    // after data-editor-ready is true. We click then check for the panel; if it doesn't
    // appear (click landed before GrapesJS event system was ready), retry once.
    const questionComp = editorPage.canvasComponent('[data-gjs-type="question-mc"]')
    await expect(questionComp).toBeVisible({ timeout: 15_000 })
    await questionComp.click()
    await editorPage.propsTab.click()

    const restoredPanel = page.locator('[data-testid="question-properties-panel"]')
    const panelVisible = await restoredPanel.isVisible().catch(() => false)
    if (!panelVisible) {
      // Retry: GrapesJS event listeners may not have been ready on first click.
      await questionComp.click()
      await editorPage.propsTab.click()
    }
    await expect(restoredPanel).toBeVisible({ timeout: 10_000 })
    const restoredTextarea = restoredPanel.locator('textarea').first()

    // The textarea must contain the user-edited value, not the default placeholder.
    await expect(restoredTextarea).toHaveValue('T601.8 regression sentinel question text', { timeout: 10_000 })
  })
})

test.describe('Question Widget: Multiple widgets on same canvas', () => {
  test.beforeEach(async ({ editorPage, page }) => {
    page.on('console', msg => {
      if (msg.type() === 'error') console.log(`[BROWSER ERROR] ${msg.text()}`)
    })
    await editorPage.addSlide()
    await editorPage.waitForCanvas()
  })

  test('T601.7 — All three question types can coexist on the same canvas', async ({ editorPage }) => {
    await editorPage.dragBlockToCanvas('Multiple Choice', 100, 150)
    await expect(editorPage.canvasComponent('[data-gjs-type="question-mc"]')).toBeVisible({ timeout: 15_000 })

    await editorPage.dragBlockToCanvas('True / False', 500, 150)
    await expect(editorPage.canvasComponent('[data-gjs-type="question-tf"]')).toBeVisible({ timeout: 15_000 })

    await editorPage.dragBlockToCanvas('Fill in the Blank', 100, 400)
    await expect(editorPage.canvasComponent('[data-gjs-type="question-fill"]')).toBeVisible({ timeout: 15_000 })
  })
})

// T611-07 — Sidebar edit + fast slide switch race condition.
// QuestionPropertiesPanel calls editor.store() synchronously on every model.set().
// The slide-switch handler also calls editor.store() synchronously before loading
// the new slide. Either path must fire a PATCH within the test timeout.
// If this test fails: check that both synchronous store() call sites are still in place.
test.describe('Question Widget: Fast slide switch race condition (T611-07)', () => {
  test.beforeEach(async ({ editorPage, page }) => {
    page.on('console', msg => {
      if (msg.type() === 'error') console.log(`[BROWSER ERROR] ${msg.text()}`)
    })
    await editorPage.addSlide()
    await editorPage.waitForCanvas()
  })

  test('T611-07 — extendedProperties edited in Props panel are preserved when switching slides before 2s debounce', async ({ editorPage, page }) => {
    test.setTimeout(60_000)

    const slides = page.locator('[data-testid="slide-item"]')
    const slideAIndex = (await slides.count()) - 1

    // Place an MC widget on slide A.
    await editorPage.dragBlockToCanvas('Multiple Choice', 300, 200)
    await expect(editorPage.canvasComponent('[data-gjs-type="question-mc"]')).toBeVisible({ timeout: 15_000 })

    // Select widget and open Props tab.
    await editorPage.canvasComponent('[data-gjs-type="question-mc"]').click()
    await editorPage.propsTab.click()

    const panel = page.locator('[data-testid="question-properties-panel"]')
    await expect(panel).toBeVisible({ timeout: 5_000 })

    // Set up a PATCH listener BEFORE the edit — QuestionPropertiesPanel calls
    // editor.store() synchronously after model.set(), so the PATCH can fire immediately.
    const patchPromise = page.waitForResponse(
      resp => resp.url().includes('/courses') && resp.request().method() === 'PATCH',
      { timeout: 15_000 },
    )

    const textarea = panel.locator('textarea').first()
    await textarea.fill('T611-07 race condition sentinel')
    await textarea.press('Tab')  // trigger onChange

    // Add slide B — addSlide() auto-navigates to the new slide, which is the rapid
    // switch being tested. Do NOT click slides.last() afterwards: addSlide() already
    // triggers editor.load() for slide B; a second click would cause a concurrent load
    // that corrupts GrapesJS internal state and crashes the editor.
    await editorPage.addSlide()
    await page.waitForTimeout(100)  // 100ms — far less than the 2s debounce

    // Wait for the PATCH that must have been triggered by the synchronous store() call.
    await patchPromise

    // Wait for slide B's canvas to be fully loaded before navigating away.
    // Without this, clicking slide A while slide B's editor.load() is still in-flight
    // causes concurrent GrapesJS loads that corrupt internal state and crash the editor.
    await editorPage.waitForCanvas()

    // Navigate back to slide A.
    await slides.nth(slideAIndex).click()
    await editorPage.waitForCanvas()
    // Give GrapesJS a moment to be fully interactive after the ready signal fires —
    // without this, click events inside the canvas iframe don't register as selections.
    await page.waitForTimeout(300)

    // Re-select the widget and verify the edited text is preserved.
    await expect(editorPage.canvasComponent('[data-gjs-type="question-mc"]')).toBeVisible({ timeout: 10_000 })
    await editorPage.canvasComponent('[data-gjs-type="question-mc"]').click()
    await editorPage.propsTab.click()

    const restoredPanel = page.locator('[data-testid="question-properties-panel"]')
    await expect(restoredPanel).toBeVisible({ timeout: 10_000 })
    const restoredTextarea = restoredPanel.locator('textarea').first()

    await expect(restoredTextarea).toHaveValue('T611-07 race condition sentinel', { timeout: 10_000 })
  })
})
