/**
 * T026.6 — AICC package → Moodle AICC activity (integration test)
 *
 * Uploads an AICC ZIP generated by packAICC() to a live Moodle instance via
 * the Moodle REST API and verifies that Moodle accepts the file.
 *
 * This test is OPT-IN: it is skipped unless the MOODLE_URL environment
 * variable is set.  Run with:
 *
 *   MOODLE_URL=http://localhost:8081 pnpm --filter @elearn-studio/scorm-packager test
 *
 * The test expects a Moodle admin account with:
 *   username: admin
 *   password: Admin1234!
 * (or override via MOODLE_USER / MOODLE_PASS env vars)
 *
 * Docker target (from docker/docker-compose.yml):
 *   docker compose --profile moodle up -d
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import * as fs from 'fs'
import * as path from 'path'
import * as os from 'os'
import AdmZip from 'adm-zip'
import { packAICC, CourseDoc } from '../index'

// ─── Environment guard ────────────────────────────────────────────────────────

const MOODLE_URL  = process.env.MOODLE_URL?.replace(/\/$/, '') ?? ''
const MOODLE_USER = process.env.MOODLE_USER ?? 'admin'
const MOODLE_PASS = process.env.MOODLE_PASS ?? 'Admin1234!'
const runMoodle   = !!MOODLE_URL

// ─── Fixtures ─────────────────────────────────────────────────────────────────

let tempDir: string
let fakePlayerPath: string

function makeCourse(overrides: Partial<CourseDoc> = {}): CourseDoc {
  return {
    _id: `aicc-moodle-${Date.now()}`,
    title: 'AICC Moodle Test Course',
    slides: [{ id: 's1', title: 'Slide 1', widgets: [] }],
    settings: { width: 1024, height: 768, passingScore: 70 },
    metadata: { identifier: `AICC_MOODLE_TEST`, version: '1.0', masteryScore: 70 },
    ...overrides,
  }
}

beforeAll(() => {
  tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'moodle-aicc-test-'))
  fakePlayerPath = path.join(tempDir, 'player.js')
  fs.writeFileSync(fakePlayerPath, '// fake player for moodle test')
})

afterAll(() => {
  if (fs.existsSync(tempDir)) {
    fs.rmSync(tempDir, { recursive: true, force: true })
  }
})

// ─── Moodle REST helpers ──────────────────────────────────────────────────────

async function getMoodleToken(): Promise<string> {
  const url = `${MOODLE_URL}/login/token.php?username=${encodeURIComponent(MOODLE_USER)}&password=${encodeURIComponent(MOODLE_PASS)}&service=moodle_mobile_app`
  const resp = await fetch(url)
  if (!resp.ok) throw new Error(`Moodle token request failed: ${resp.status} ${resp.statusText}`)
  const body = await resp.json() as { token?: string; error?: string }
  if (body.error || !body.token) throw new Error(`Moodle auth error: ${body.error ?? 'no token'}`)
  return body.token
}

async function moodleRestCall(token: string, fn: string, params: Record<string, string>): Promise<unknown> {
  const form = new URLSearchParams({ wstoken: token, wsfunction: fn, moodlewsrestformat: 'json', ...params })
  const resp = await fetch(`${MOODLE_URL}/webservice/rest/server.php`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: form.toString(),
  })
  if (!resp.ok) throw new Error(`Moodle REST error: ${resp.status} ${resp.statusText}`)
  const data = await resp.json() as { exception?: string; message?: string }
  if (data.exception) throw new Error(`Moodle API exception: ${data.message ?? data.exception}`)
  return data
}

async function uploadFile(token: string, filePath: string, fileName: string): Promise<number> {
  const fileBytes = fs.readFileSync(filePath)
  const form = new FormData()
  form.append('token', token)
  form.append('filearea', 'draft')
  form.append('itemid', '0')
  form.append('file_1', new Blob([fileBytes], { type: 'application/zip' }), fileName)

  const resp = await fetch(`${MOODLE_URL}/webservice/upload.php`, {
    method: 'POST',
    body: form,
  })
  if (!resp.ok) throw new Error(`Moodle upload failed: ${resp.status} ${resp.statusText}`)
  const result = await resp.json() as Array<{ itemid?: number; error?: string }>
  if (!Array.isArray(result) || result.length === 0) {
    throw new Error('Moodle upload returned unexpected response')
  }
  if (result[0].error) throw new Error(`Moodle upload error: ${result[0].error}`)
  const itemid = result[0].itemid
  if (!itemid) throw new Error('Moodle upload response missing itemid')
  return itemid
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe.skipIf(!runMoodle)('T026.6 — AICC package → Moodle upload', () => {
  let token: string

  beforeAll(async () => {
    if (!runMoodle) return
    token = await getMoodleToken()
  })

  it('authenticates against Moodle and receives a token', async () => {
    expect(typeof token).toBe('string')
    expect(token.length).toBeGreaterThan(0)
  })

  it('packAICC produces a valid ZIP with AICC descriptor files', async () => {
    const course   = makeCourse()
    const outputDir = path.join(tempDir, 'aicc-out-verify')
    const zipPath  = await packAICC(course, outputDir, { playerPath: fakePlayerPath })

    expect(fs.existsSync(zipPath)).toBe(true)

    const zip = new AdmZip(zipPath)
    const entries = zip.getEntries().map(e => e.entryName)

    // AICC requires at least a .au file for Moodle to recognise the package
    expect(entries.some(e => e.endsWith('.au'))).toBe(true)
    expect(entries.some(e => e.endsWith('.crs'))).toBe(true)
    expect(entries.some(e => e.endsWith('.des'))).toBe(true)
    expect(entries.some(e => e.endsWith('.cst'))).toBe(true)
    expect(entries).toContain('index.html')
    expect(entries).toContain('player.js')
  })

  it('uploads AICC ZIP to Moodle draft file area and receives an itemid', async () => {
    const course   = makeCourse({ title: 'Upload Test ' + Date.now() })
    const outputDir = path.join(tempDir, 'aicc-out-upload')
    const zipPath  = await packAICC(course, outputDir, { playerPath: fakePlayerPath })
    const fileName = path.basename(zipPath)

    const itemid = await uploadFile(token, zipPath, fileName)
    expect(typeof itemid).toBe('number')
    expect(itemid).toBeGreaterThan(0)
  })

  it('Moodle REST API responds to core_webservice_get_site_info', async () => {
    const info = await moodleRestCall(token, 'core_webservice_get_site_info', {}) as {
      sitename?: string
      username?: string
    }
    expect(typeof info.sitename).toBe('string')
    expect(info.username?.toLowerCase()).toBe(MOODLE_USER.toLowerCase())
  })
})

// ─── Offline smoke tests (always run) ────────────────────────────────────────

describe('packAICC output structure (offline)', () => {
  it('produces a zip file ending in _aicc.zip', async () => {
    const course    = makeCourse({ title: 'Offline AICC Smoke' })
    const outputDir = path.join(tempDir, 'aicc-smoke')
    const zipPath   = await packAICC(course, outputDir, { playerPath: fakePlayerPath })

    expect(zipPath).toMatch(/_aicc\.zip$/)
    expect(fs.existsSync(zipPath)).toBe(true)
  })

  it('.au file contains AU_ID and File_Name=index.html', async () => {
    const course    = makeCourse()
    const outputDir = path.join(tempDir, 'aicc-au-check')
    const zipPath   = await packAICC(course, outputDir, { playerPath: fakePlayerPath })

    const zip = new AdmZip(zipPath)
    const auEntry = zip.getEntries().find(e => e.entryName.endsWith('.au'))
    expect(auEntry).toBeDefined()

    const auContent = auEntry!.getData().toString('utf8')
    expect(auContent).toContain('[AU]')
    expect(auContent).toContain('AU_001')
    expect(auContent).toContain('index.html')
  })

  it('.crs file contains Course_ID and Mastery_Score', async () => {
    const course    = makeCourse()
    const outputDir = path.join(tempDir, 'aicc-crs-check')
    const zipPath   = await packAICC(course, outputDir, { playerPath: fakePlayerPath })

    const zip = new AdmZip(zipPath)
    const crsEntry = zip.getEntries().find(e => e.entryName.endsWith('.crs'))
    expect(crsEntry).toBeDefined()

    const crsContent = crsEntry!.getData().toString('utf8')
    expect(crsContent).toContain('[Course]')
    expect(crsContent).toContain('Mastery_Score=70')
  })

  it('index.html contains HACP bridge script', async () => {
    const course    = makeCourse()
    const outputDir = path.join(tempDir, 'aicc-html-check')
    const zipPath   = await packAICC(course, outputDir, { playerPath: fakePlayerPath })

    const zip = new AdmZip(zipPath)
    const htmlEntry = zip.getEntry('index.html')
    expect(htmlEntry).toBeDefined()

    const htmlContent = htmlEntry!.getData().toString('utf8')
    expect(htmlContent).toContain('HACP bridge')
  })
})
